name: utility_yaml
description: This is just a packages that lets me use YamlMap in a way I'm comfortable with.
version: 1.1.2
repository: https://github.com/MineStarAS/utility_yaml

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  yaml: ^3.1.1


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0